### PR TITLE
Fixed blurry text

### PR DESCRIPTION
**Pull request by jordi-7**

### CODE REVIEW

**Comment by kas** [comment]
Hi Jordi:

I appreciate you opening this pull request. I tested this fix and it seems that some percentages are unreadable. For example, at 1280x800 resolution, 94% looks like [this](https://i.imgur.com/rWXHrz2.png). I tested other `TextRenderingHint`s and I noticed that the current `TextRenderingHint.AntiAlias` was the most legible. The main motivation behind this project was to provide a convenient way to read your battery percentage on low-resolution devices such as the [GPD Win](https://www.reddit.com/r/gpdwin). It is critical that the percentage can be legible at low resolutions.

**Comment by jordiid96** [comment]
Hi,
My solution looked better on my computer, but I get your point, yours look better in lower resolutions.

**Comment by xasweil** [comment]
@kas , you can provide two versions: for devices with low resolution and high. I think this will solve all the problems and everyone will be happy.

**Comment by kas** [comment]
@xasweil Thank you for the suggestion. That is a great solution. To build off of what you suggested, I am thinking that we can eliminate the need to supply two versions by checking the system resolution each time the percentage is updated. Since we know that the application is only supported on Windows 10, it shouldn't be difficult to implement a way to check the current resolution.

One question that comes to mind: what resolution is the cutoff for low/high resolutions?

If this proves to be too difficult to implement we will just offer two separate versions. I am open to your input!

**Comment by xasweil** [comment]
@kas , I think low resolution is between 1366x768 and 1600x900, high begins with 1920x1080. It's also not excluded that the fix for higher resolutions will also work correctly on resolutions above FullHD, but I can't check it. I think you should release two versions on the public test and collect more user feedback, to understand it.

**Comment by jordiid96** [comment]
You could also add a context menu to the tray icon and let the user choose.

**Comment by xasweil** [comment]
@kas , look at this project: [BrightnessTray](https://github.com/navhaxs/BrightnessTray). The digits look just gorgeous with my resolution. Maybe you can find something useful in the source code.

**Comment by laureanoruiz** [comment]
Yes, indeed. I have a 14" screen with FHD resolution and chaging "Bitmap bitmapText = new Bitmap(16, 16);" bitmap to 32,32 and the font size to 24 has fixed the blurry text.
So, the solution would be implementing two modes depending on the screen resolution as BrightnessTray does.

**Comment by kas** [comment]
@laureanoruiz Thank you for confirming that. We can implement what you described.

I think that for simplicity's sake (especially for the end user) we should judge which bitmap dimensions/font size to use automatically depending on the current resolution. @xasweil I agree with your decisions for what constitutes low resolution and high resolution. I will not be able to test this past `1920x1200` though.

**Comment by kas** [comment]
Hey solo5star unfortunately I don't have a small screen device to test with. With 1.2.0 I bumped the font size, which helped with blurriness. Today I tried using the TextRenderingHint from your commit and I can't tell a difference (but my resolution is 3840x2160, 250% scale). At this point I'm not sure we need to take the fix, please reopen if you disagree

**Pull request closed without merging**
